name: Liquid GitHub Actions
on:
  push:
  pull_request:
  release:
    types: [published, created, edited]

jobs:
  macOS_test:
    name: macOS_test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install macOS dependencies
        run: brew install openssl@1.1 ccache automake
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          target: wasm32-unknown-unknown
      - name: check
        run: ./scripts/check.sh -e

  ubuntu_test:
    name: ubuntu_test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          target: wasm32-unknown-unknown
      - name: check
        run: ./scripts/check.sh -e

  win_test:
    name: win_test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
      - name: check
        shell: cmd
        run: ./scripts/check-workspace.bat
